### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by Its-Vichy** [pneb/Encrypter#1]
stop use tkinter, use QT bro insane 2022

**Comment by pneb** [comment]
bro alright, I'll later

**Comment by pneb** [comment]
there 🤓

**Comment by Its-Vichy** [comment]
... and QT disigner to make cool ui not shit with 1 button

**Comment by pneb** [comment]
okay I will later, chill

**Comment by pneb** [comment]
There bro, added new 2 buttons, and fixed the bg color 🤓

**Comment by Its-Vichy** [comment]
bro you hurt my eyes !

**Comment by pneb** [comment]
okay, later I'll completely rewrite the GUI
